export default [
  {
    name: "documents",
    options: { label: "اسناد", icon: "clipboard" },
    list: "/documents",
    show: "/documents/:id",
    create: "/documents/create",
    edit: "/documents/:id/edit",
  },
  // {
  //     name: "customers",
  //     list: "/customers",
  //     options: {label: "مشتریان", icon: "user-group"},
  // },
  // {
  //     name: "customers",
  //     identifier: "customers_company",
  //     options: {label: "مشتریان حقوقی", hide: true},
  //     list: '/customers/company',
  //     show: '/customers/company/:id',
  //     create: '/customers/company/create',
  //     edit: '/customers/company/:id/edit',
  // },
  // {
  //     name: "customers",
  //     identifier: "customers_person",
  //     options: {label: "مشتریان حقیقی", hide: true},
  //     list: '/customers/person',
  //     show: '/customers/person/:id',
  //     create: '/customers/person/create',
  //     edit: '/customers/person/:id/edit',
  // },
  {
    name: "managers",
    options: { label: "مدیران", icon: "award" },
    list: "/managers",
    show: "/managers/:id",
    create: "/managers/create",
    edit: "/managers/:id/edit",
  },
  {
    name: "staffs",
    options: { label: "پشتیبان ها", icon: "headphones", hide: true },
    list: "/support/staffs",
    show: "/support/staffs/:id",
    create: "/support/staffs/create",
    edit: "/support/staffs/:id/edit",
  },
  {
    name: "notifications",
    options: { label: "اطلاعیه‌ها", icon: "bell" },
    list: "/notifications",
    show: "/notifications/:id",
  },
  {
    name: "profile",
    show: "/profile",
    create: "/profile/edit",
    identifier: "profile",
    meta: {
      label: "پروفایل",
      hide: true,
    },
  },
];
