export default [
    {
        name: "books",
        meta: {label: "کتاب‌ها", icon: "book",},
        identifier: "books",
        list: '/books',
        show: '/books/:id',
        create: '/books/create',
        edit: '/books/:id/edit',
    },
    {
        name: "articles",
        meta: {label: "مقاله‌ها", icon: "article",},
        identifier: "articles",
        list: '/articles',
        show: '/articles/:id',
        create: '/articles/create',
        edit: '/articles/:id/edit',
    },
    {
        name: "speeches",
        meta: {label: "سخنرانی‌ها", icon: "speech",},
        identifier: "speeches",
        list: '/speeches',
        show: '/speeches/:id',
        create: '/speeches/create',
        edit: '/speeches/:id/edit',
    },
    {
        name: "videos",
        meta: {label: "فیلم‌ها", icon: "video",},
        identifier: "videos",
        list: '/videos',
        show: '/videos/:id',
        create: '/videos/create',
        edit: '/videos/:id/edit',
    },
    {
        name: "banners",
        meta: {label: "بنر‌ها", icon: "banner",},
        identifier: "banners",
        list: '/banners',
        show: '/banners/:id',
        create: '/banners/create',
        edit: '/banners/:id/edit',
    },
    {
        name: "categories",
        meta: {label: "دسته‌ها", icon: "square-2x2",},
        identifier: "categories",
        list: '/categories',
        show: '/categories/:id',
        create: '/categories/create',
        edit: '/categories/:id/edit',
    },
    {
        name: "comments",
        meta: {label: "دیدگاه‌ها", icon: "comment",},
        identifier: "comments",
        list: '/comments',
        show: '/comments/:id',
        create: '/comments/create',
        edit: '/comments/:id/edit',
    },
    {
        name: "contributors",
        list: "/contributors",
        options: {label: "کاربران", icon: "user-group"},
    },
    {
        name: "contributors",
        identifier: "contributors_company",
        options: {label: "مشتریان حقوقی", hide: true},
        list: '/contributors/company',
        show: '/contributors/company/:id',
        create: '/contributors/company/create',
        edit: '/contributors/company/:id/edit',
    },
    {
        name: "contributors",
        identifier: "contributors_person",
        options: {label: "مشتریان حقیقی", hide: true},
        list: '/contributors/person',
        show: '/contributors/person/:id',
        create: '/contributors/person/create',
        edit: '/contributors/person/:id/edit',
    },
    {
        name: "moderators",
        options: {label: "مسئولان محتوا", icon: "document-text",},
        list: '/moderators',
        show: '/moderators/:id',
        create: '/moderators/create',
        edit: '/moderators/:id/edit',
    },
    // {
    //     name: "managers",
    //     options: {label: "مدیران", icon: "award",},
    //     list: '/managers',
    //     show: '/managers/:id',
    //     create: '/managers/create',
    //     edit: '/managers/:id/edit',
    // },
    // {
    //     name: "notifications",
    //     options: {label: "اطلاعیه‌ها", icon: "bell",},
    //     list: '/notifications',
    //     show: '/notifications/:id',
    // },
    {
        name: "profile",
        show: "/profile",
        create: "/profile/edit",
        identifier: 'profile',
        meta: {
            label: 'پروفایل',
            hide: true,
        }
    },
];